// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfoewtoajdjhyrlajtga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mb2V3dG9hamRqaHlybGFqdGdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTAxODcsImV4cCI6MjA3MTE4NjE4N30.RQGyjDjfK1Oo1O_qyH9CuGQ0KmUhQnwL8qnizUrXZeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});